seed: 42
device: auto

data:
  batch_size: 128
  val_ratio: 0.1
  num_workers: 0

model:
  file: models/resnet.py
  class_name: MiniResNet
  kwargs:
    activation: relu
    norm: batchnorm
    dropout: 0.2

train:
  run_name: resnet_adamw_plateau
  epochs: 15
  optimizer:
    name: adamw
    lr: 0.001
    weight_decay: 0.01
  scheduler:
    name: plateau
    patience: 3      # 如果连续 3 个 epoch loss 不下降则调整
    factor: 0.5      # 学习率减半
    min_lr: 0.000001
  regularization:
    type: l2
    l2_lambda: 0.0001